# Generated by Django 4.2.21 on 2025-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved_affiliate",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is an approved affiliate",
            ),
        ),
    ]
