# Generated by Django 4.2.21 on 2025-06-05 22:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        help_text="Unique referral code for the affiliate",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="Affiliate's website or social media profile",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe Connect"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="paypal",
                        max_length=20,
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(
                        blank=True,
                        help_text="PayPal email for payouts",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "stripe_connect_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect account ID",
                        max_length=100,
                    ),
                ),
                (
                    "bank_account_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Encrypted bank account details",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="Commission rate as percentage (default 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "minimum_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Minimum amount required for payout",
                        max_digits=10,
                    ),
                ),
                (
                    "application_reason",
                    models.TextField(
                        help_text="Reason for wanting to become an affiliate"
                    ),
                ),
                (
                    "marketing_experience",
                    models.TextField(
                        blank=True,
                        help_text="Previous marketing or affiliate experience",
                    ),
                ),
                (
                    "traffic_sources",
                    models.TextField(
                        blank=True,
                        help_text="Where affiliate plans to promote (social media, website, etc.)",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_affiliates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Profile",
                "verbose_name_plural": "Affiliate Profiles",
            },
        ),
        migrations.CreateModel(
            name="AffiliateResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("email_template", "Email Template"),
                            ("social_template", "Social Media Template"),
                            ("landing_page", "Landing Page"),
                            ("tutorial", "Tutorial"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("download_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Affiliate Resource",
                "verbose_name_plural": "Affiliate Resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referrer_url", models.URLField(blank=True)),
                ("landing_page", models.URLField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_clicks",
                        to="affiliates.affiliateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Click",
                "verbose_name_plural": "Referral Clicks",
            },
        ),
        migrations.CreateModel(
            name="ReferralConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversion_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Initial value of the conversion",
                        max_digits=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "referral_click",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion",
                        to="affiliates.referralclick",
                    ),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_source",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Conversion",
                "verbose_name_plural": "Referral Conversions",
            },
        ),
        migrations.CreateModel(
            name="CommissionLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original subscription amount",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission rate applied",
                        max_digits=5,
                    ),
                ),
                (
                    "amount_earned",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission amount earned",
                        max_digits=10,
                    ),
                ),
                (
                    "month_year",
                    models.CharField(help_text="Format: YYYY-MM", max_length=7),
                ),
                ("billing_period_start", models.DateTimeField()),
                ("billing_period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payout_method", models.CharField(blank=True, max_length=20)),
                ("payout_transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "payout_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_ledger",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "conversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_entries",
                        to="affiliates.referralconversion",
                    ),
                ),
                (
                    "referred_user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_entries",
                        to="project_core.usersubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Ledger Entry",
                "verbose_name_plural": "Commission Ledger Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="referralconversion",
            index=models.Index(
                fields=["affiliate", "timestamp"], name="affiliates__affilia_f89c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralconversion",
            index=models.Index(
                fields=["referred_user"], name="affiliates__referre_e517ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralconversion",
            index=models.Index(
                fields=["timestamp"], name="affiliates__timesta_a334e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(
                fields=["affiliate", "timestamp"], name="affiliates__affilia_8c6bb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="affiliates__ip_addr_75c643_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referralclick",
            index=models.Index(
                fields=["timestamp"], name="affiliates__timesta_6afd1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionledger",
            index=models.Index(
                fields=["affiliate", "month_year"],
                name="affiliates__affilia_264aa5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionledger",
            index=models.Index(
                fields=["status", "created_at"], name="affiliates__status_7e0fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionledger",
            index=models.Index(
                fields=["month_year"], name="affiliates__month_y_f04991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateprofile",
            index=models.Index(
                fields=["referral_code"], name="affiliates__referra_17be4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateprofile",
            index=models.Index(
                fields=["status", "approved_at"], name="affiliates__status_cd1113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateprofile",
            index=models.Index(
                fields=["created_at"], name="affiliates__created_ba63d7_idx"
            ),
        ),
    ]
