# Generated by Django 4.2.21 on 2025-06-03 20:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadCreditPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Package name (e.g., 'Boost Pack')", max_length=100
                    ),
                ),
                ("description", models.TextField(help_text="Package description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "lead_count",
                    models.IntegerField(
                        help_text="Number of leads included in this package",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_buyer_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target subscription plan (optional recommendation)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_core.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Credit Package",
                "verbose_name_plural": "Lead Credit Packages",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_purchased",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lead credit package purchased (for one-time purchases)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.leadcreditpackage",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related subscription (for subscription payments)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_core.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment History",
                "verbose_name_plural": "Payment Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLeadCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credits_purchased",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "credits_used",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When these credits expire (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.leadcreditpackage",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_credits",
                        to="subscriptions.paymenthistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Lead Credit",
                "verbose_name_plural": "User Lead Credits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUpgradeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "proration_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proration amount for upgrade/downgrade",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the change should take effect",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_requests",
                        to="project_core.usersubscription",
                    ),
                ),
                (
                    "requested_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_core.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Upgrade Request",
                "verbose_name_plural": "Subscription Upgrade Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionCancellationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("too_expensive", "Too Expensive"),
                            ("not_enough_features", "Not Enough Features"),
                            ("technical_issues", "Technical Issues"),
                            ("switching_service", "Switching to Another Service"),
                            ("business_closure", "Business Closure"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Additional feedback"),
                ),
                (
                    "cancel_immediately",
                    models.BooleanField(
                        default=False,
                        help_text="Cancel immediately vs. at end of billing period",
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When cancellation will take effect",
                        null=True,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to="project_core.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Cancellation Request",
                "verbose_name_plural": "Subscription Cancellation Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_d33c13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["payment_gateway", "status"],
                name="subscriptio_payment_215255_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["transaction_id"], name="subscriptio_transac_ef3e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["created_at"], name="subscriptio_created_df3f57_idx"
            ),
        ),
    ]
