# Generated by Django 4.2.21 on 2025-06-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_panel_admin_u_f7a30b_idx",
            old_name="admin_panel_adminlo_admin_u_8b4c9f_idx",
        ),
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_panel_action__9cc5cc_idx",
            old_name="admin_panel_adminlo_action__d7e8c2_idx",
        ),
        migrations.RenameIndex(
            model_name="adminlog",
            new_name="admin_panel_target__7154e0_idx",
            old_name="admin_panel_adminlo_target__f9a3e6_idx",
        ),
        migrations.RenameIndex(
            model_name="contenttemplate",
            new_name="admin_panel_templat_efda5b_idx",
            old_name="admin_panel_content_templat_47b8a9_idx",
        ),
        migrations.RenameIndex(
            model_name="contenttemplate",
            new_name="admin_panel_status_c6865d_idx",
            old_name="admin_panel_content_status_d4c8e1_idx",
        ),
        migrations.RenameIndex(
            model_name="contenttemplate",
            new_name="admin_panel_created_5a1c64_idx",
            old_name="admin_panel_content_created_c9f7e3_idx",
        ),
        migrations.RenameIndex(
            model_name="systemsettings",
            new_name="admin_panel_categor_d047e1_idx",
            old_name="admin_panel_systemse_categor_9f7e64_idx",
        ),
        migrations.RenameIndex(
            model_name="systemsettings",
            new_name="admin_panel_key_44b980_idx",
            old_name="admin_panel_systemse_key_9a8b4c_idx",
        ),
    ]
